FROM php:7.4-fpm

RUN apt-get update && apt-get install -y

RUN apt-get update && apt-get install -y --no-install-recommends \
        git \
        zlib1g-dev \
        libxml2-dev \
        libzip-dev \
        curl \
    && docker-php-ext-install \
        zip \
        pdo \
        pdo_mysql \
        intl

RUN docker-php-ext-enable pdo_mysql

RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
COPY . /var/www/
WORKDIR /var/www/